spring.application.name=coop-edit-backend

spring.config.import=classpath:/config/env.properties

app.jwt.access.secret=${JWT_ACCESS_SECRET}
app.jwt.refresh.secret=${JWT_REFRESH_SECRET}
app.jwt.access.expiration-in-ms=36000000
app.jwt.refresh.expiration-in-ms=86400000000

app.room.keep-alive-in-min=86400000

spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.authorizationserver.issuer=car-rental
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.ricramiel=DEBUG

spring.profiles.active=dev

#spring.jpa.database=postgresql
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param